name: flavor_server
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.14.4 <3.0.0'

dependencies:
  path: ^1.7.0
  shelf: ^1.2.0
  shelf_router: ^1.1.1
  shelf_static: ^1.1.0
  crypto: ^3.0.0
  # mongo_dart: ^0.7.3
  dart_jsonwebtoken: ^2.4.0
  envify: ^2.0.2
  uuid: ^3.0.0
  # basic_utils: ^3.7.0
  logger: ^1.1.0
  # neat_cache: ^2.0.1
  flavor_auth:
    path: ../flavor_auth
  flavor_redis:
    path: ../flavor_redis
  flavor_dartis:
    path: ../../flavor_dartis

dev_dependencies:
  http: ^0.13.4
  pedantic: ^1.9.0
  test: ^1.14.4
  # envify_generator: ^2.0.2
  build_runner: ^1.11.1
