name: flavor_auth
description: A starting point for Dart libraries or applications.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
#  path: ^1.7.0
  dart_jsonwebtoken: ^2.4.0
  flavor_http:
    path: ../flavor_http
  flavor_redis:
    path: ../flavor_redis
  uuid: ^3.0.5
  # redis: ^2.1.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
  args: ^1.6.0
  logger: 
  build_runner: ^1.0.0
  json_serializable: ^3.3.0