name: flavor_http
description: Flavor Http services
publish_to: 'none'

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  http: 
   
 

dev_dependencies:
  build_runner: ^1.0.0
  json_serializable: ^3.3.0
  
# flutter:
#   uses-material-design: true

  # assets:
  #   - assets/
  #   - assets/images/
  #   - assets/images/people/
